name: ci

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Lint
        run: yarn lint
        env:
          CI: true
